# Generated by Django 3.1.2 on 2021-07-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_auto_20201106_2122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='huyen',
            options={'verbose_name': '4. Thống kê Quận/Huyện', 'verbose_name_plural': '4. Thống kê Quận/Huyện'},
        ),
        migrations.AlterModelOptions(
            name='thon',
            options={'verbose_name': 'Thôn/Ấp', 'verbose_name_plural': 'Thôn/Ấp'},
        ),
        migrations.AlterModelOptions(
            name='tinh',
            options={'verbose_name': '3. Thống kê Tỉnh/TP', 'verbose_name_plural': '3. Thống kê Tỉnh/TP'},
        ),
        migrations.AlterModelOptions(
            name='xa',
            options={'verbose_name': '5. Thống kê Xã/Phường', 'verbose_name_plural': '5. Thống kê Xã/Phường'},
        ),
        migrations.AddField(
            model_name='cuuho',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalhodan',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='hodan',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='huyen',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='nguonluc',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='thon',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='tinh',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='tinhnguyenvien',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='tintuc',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='trangthaihodan',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='xa',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='huyen',
            name='name',
            field=models.TextField(blank=True, default='', verbose_name='Quận/Huyện'),
        ),
        migrations.AlterField(
            model_name='thon',
            name='name',
            field=models.TextField(blank=True, default='', verbose_name='Thôn/Ấp'),
        ),
        migrations.AlterField(
            model_name='tinh',
            name='name',
            field=models.TextField(blank=True, default='', verbose_name='Tỉnh/TP'),
        ),
        migrations.AlterField(
            model_name='tintuc',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Nội Dung'),
        ),
        migrations.AlterField(
            model_name='tintuc',
            name='title',
            field=models.TextField(blank=True, default='', verbose_name='Tiêu Đề'),
        ),
        migrations.AlterField(
            model_name='xa',
            name='name',
            field=models.TextField(blank=True, default='', verbose_name='Xã/Phường'),
        ),
    ]
